#!/bin/bash

ll_file=$1
name=$(basename -s .ll $1)
#name=${ll_file#logic-layouts/}
parent_name=$(dirname ${ll_file#logic-layouts/})

echo $ll_file $name
[ ! -d "bin/$parent_name" ] && mkdir -p "bin/$parent_name"

bin/parser -file $ll_file > "bin/$parent_name/$name"
chmod 755 "bin/$parent_name/$name"
